#!/bin/bash

alias criticalcompass="ssh -p 500 dean@criticalcompass.com"
alias pluto2="ssh deant@192.168.0.56"
alias vilmos2="ssh deant@192.168.0.64"
alias lechuck="ssh -p 600 dean@192.168.1.20"
alias weather="curl http://wttr.in/melbourne"
alias torrents="transmission-remote-cli -c 192.168.1.20:8080"
