#! /bin/sh

sxhkd &
hsetroot -full /home/whoami/Pictures/firewatch.jpg
bspc config border_width         2
bspc config window_gap          30
bspc config top_padding         38
bspc config left_padding        38
bspc config right_padding       38
bspc config bottom_padding      38


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true

bspc config normal_border_color "#1f1d21"
bspc config focused_border_color "#be5e1e"
bspc config presel_feedback_color "#be5e1e"


bspc monitor -d     

bspc rule -a Steam desktop=^3 follow=on split_dir=right
bspc rule -a URxvt:updates state=floating
bspc rule -a URxvt:pulsemixer state=floating
bspc rule -a URxvt:mutt desktop=^2 follow=on
bspc rule -a URxvt:weechat desktop=^2 follow=on
bspc rule -a Gimp desktop=^4 follow=on
bspc rule -a URxvt:vpn desktop=^5 follow=on state=floating
bspc rule -a URxvt:upass state=floating

